### ISSUE TITLE
More detailed tutorial on sensor calibration 

### ISSUE THREAD

**Issue by 2000222** [rickstaa/panda_autograsp#187]
Hello, thanks for your amazing contributions 😄. Now I am using the "melodic-devel-realsense branch" for grasping. And currently I can successfully run "roslaunch panda_autograsp panda_autograsp.launch", but I feel a little confused about the "sensor calibration" part since I execute the launch but get the inclined platform of the whole camera information, so I think I need to make new eye-hand calibration to change the "main_config.cfg" and "calib_frames_poses.yaml". So if you are comfortable, could u help me for more detailed "sensor calibration" tutorial on Intel Realsense D435 camera. Thank u very much ! 
In addition, I can not run "rosrun panda_autograsp panda_autograsp_cli.launch", it needs to independently execute panda_autograsp_cli.py 😢.

**Comment by rickstaa** [comment]
Hey @200022. Thanks for your interest in this repository. As I do not own a RealSense camera, I used a friend's camera when a student asked if he could use my software with the RealSense. I, however, did not thoroughly test [the realsense branch](https://github.com/rickstaa/panda-autograsp/tree/noetic-devel-realsense. I suspect the calibration module does not yet  work with the ReaSense camera:

https://github.com/rickstaa/panda-autograsp/blob/1df0e7a4e71b6f98f3eb4116aed8d754ae1a1674/panda_autograsp/scripts/chessboard_calibration.py#L102-L110

Instead, I used the dynamic reconfigure window to alight my frames right (see https://rickstaa.dev/panda-autograsp/usage/usage.html#dynamic-reconfigure-window). It should not be hard to make this calibration script work on the [real sense branch](https://github.com/rickstaa/panda-autograsp/tree/noetic-devel-realsense). Unfortunately, I don't have access to a RealSense camera at the moment, but you can give it a try.

You are right about the `panda_autograsp_cli.launch` file. The documentation incorrect and `rosrun panda_autograsp panda_autograsp_cli.launch` should be `rosrun panda_autograsp panda_autograsp_cli.py` as I did not create a launchfile for running this simple script. I created #188 to fix this.

**Comment by rickstaa** [comment]
On second thought. 🤔 I vaguely remember I got it to also work with the RealSense camera (see the commits made on the  [noetic-devel-realsense](https://github.com/rickstaa/panda-autograsp/compare/noetic-devel-realsense) branch). I, however, can not verify this since I do not own a RealSense camera. Please let me know if you run into any problems. Maybe I can help you debug it.

**Comment by rickstaa** [comment]
Closed due to inactivity.
